# -*- coding: utf-8 -*-
"""NLP Day-18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrmTq4YrxDCMPo9X1xMKBbpp3CH1lePe
"""

!pip install transformers torch

from transformers import pipeline

# Commented out IPython magic to ensure Python compatibility.
from transformers import pipeline
senti = pipeline('sentiment-analysis')
reviews = [
'This movie was absolutely breathtaking! A masterpiece.',
'Terrible acting, boring plot. Wasted 2 hours of my life.',
'It was okay. Nothing special but not bad either.',
'Shah Rukh Khan was brilliant. Loved every minute!',
'Ram is more attractive than jayanth ani evaro chepparu',
'KSRM is a great college in asia',
            "ram is worest boy",
'charan is bad boy but brillant and worest,dirty guy  ',
"# NEGATIVE (55.2-

# %) | It was okay. Nothing special but not bad either...."

]
results = senti(reviews) # pass a list — processes all at once
for review, result in zip(reviews, results):
  label = result['label'] # 'POSITIVE' or 'NEGATIVE'
  score = result['score'] # confidence: 0.0 to 1.0
  print(f'{label} ({score:.1%}) | {review[:50]}...')
# POSITIVE (99.8%) | This movie was absolutely breathtaking! A masterp...
# NEGATIVE (99.9%) | Terrible acting, boring plot. Wasted 2 hours of m...
# NEGATIVE (55.2%) | It was okay. Nothing special but not bad either....
# POSITIVE (99.1%) | Shah Rukh Khan was brilliant. Loved every minute!.

from transformers import pipeline
# Zero-shot: classify without any task-specific training
classifier = pipeline('zero-shot-classification',
model='facebook/bart-large-mnli')
text = 'ksrm is a college of engineering . in aiml we have best students in non crt but cse are worst except few(nen itey aswitha ni analey)'
labels = ['technology','course','computer science','artificial intellignece']
result = classifier(text, candidate_labels=labels)
for label, score in zip(result['labels'], result['scores']):
   print(f'{label:15} {score:.1%}')

from transformers import pipeline
# Zero-shot: classify without any task-specific training
classifier = pipeline('zero-shot-classification',
model='facebook/bart-large-mnli')
text = ' s1 not loves s2 and s2  loves s1'
labels = ["their are lovers","not lovers"]
result = classifier(text, candidate_labels=labels)
for label, score in zip(result['labels'], result['scores']):
   print(f'{label:15} {score:.1%}')



import transformers
print(transformers.__file__)
print(transformers.__version__)

!pip install --force-reinstall transformers==4.44.2 tokenizers==0.19.1 --break-system-packages

from transformers import pipeline

summariser = pipeline(
    task="summarization",
    model="facebook/bart-large-cnn"
)

long_text = """
The Indian Space Research Organisation (ISRO) successfully launched its
latest Earth observation satellite from the Satish Dhawan Space Centre in
Sriharikota. The satellite carries high-resolution cameras capable of
imaging at 0.5-metre resolution, making it among the most advanced Earth
observation tools deployed. The data will be used for agriculture
monitoring, disaster management, and urban planning.
"""

summary = summariser(
    long_text,
    max_length=20,
    min_length=15,
    do_sample=False,
    truncation=True
)

print(summary[0]["summary_text"])

from transformers import pipeline

summariser = pipeline(
    task="summarization",
    model="facebook/bart-large-cnn"
)

long_text = """
Enthusiastic engineering student specializing in AI/ML,
with a growing interest in Prompt Engineering andGenerative AI.
Skilled in Python, SQL, and problem-solving, with hands-on experience in building
small AIprojects and exploring effective prompt design.
Passionate about leveraging AI to solve real-world problemsand eager to learn, innovate, and contribute to a dynamic technology environment.
"""

summary = summariser(
    long_text,
    max_length=50,
    min_length=20,
    do_sample=False,
    truncation=True
)

print(summary[0]["summary_text"])

from transformers import pipeline
qa = pipeline('question-answering',
model='deepset/bert-base-cased-squad2')
context = '''
Sachin Tendulkar played for India for 24 years from 1989 to 2013.
He scored 100 international centuries and 15,921 Test runs.
He was awarded the Bharat Ratna in 2014.
'''
questions = [
'How many international centuries did Sachin score?',
'When did Sachin Tendulkar retire?',
'What award did he receive in 2014?',
]
for q in questions:
  answer = qa(question=q, context=context)
  print(f'Q: {q}')
  print(f'A: {answer["answer"]} (confidence: {answer["score"]:.1%})')
# Q: How many international centuries did Sachin score?
# A: 100 (confidence: 94.2%)

from transformers import pipeline
qa = pipeline('question-answering',
model='deepset/bert-base-cased-squad2')
context = '''
My name is jayanth kumar. i am from kadapa.in ksrm student Enthusiastic engineering student specializing in AI/ML,
with a growing interest in Prompt Engineering andGenerative AI.
 Skilled in Python, SQL, and problem-solving, with hands-on experience in building
 small AIprojects and exploring effective prompt design. Passionate about leveraging
 AI to solve real-world problemsand eager to learn, innovate,
 and contribute to a dynamic technology environment.
'''
questions = [
"which college studing?",
 'What his name?',
'What are their skills?',
]
for q in questions:
  answer = qa(question=q, context=context)
  print(f'Q: {q}')
  print(f'A: {answer["answer"]} (confidence: {answer["score"]:.1%})')
# Q: How many international centuries did Sachin score?
# A: 100 (confidence: 94.2%)

from transformers import pipeline
# Helsinki-NLP models for 1000+ language pairs
# Model naming: Helsinki-NLP/opus-mt-{source}-{target}
en_hi = pipeline('translation',
model='Helsinki-NLP/opus-mt-en-hi')
texts = [
'Machine learning is changing the world.',
'I love cricket and Bollywood movies.',
]
for text in texts:
  translated = en_hi(text)[0]['translation_text']
  print(f'EN: {text}')
  print(f'HI: {translated}')
# EN: Machine learning is changing the world.
# HI: mshyn lrnng duniya bdl rhi hai.
# For French: pipeline('translation', model='Helsinki-NLP/opus-mt-en-fr')

from transformers import pipeline

# English -> Telugu Translation
en_te = pipeline(
    "translation",
    model="facebook/nllb-200-distilled-600M"
)
texts = [
    "ram where your annaiversary !.",
    "ram loves sita.",
]

for text in texts:
    translated = en_te(
        text,
        src_lang="eng_Latn",
        tgt_lang="tel_Telu"
    )[0]["translation_text"]

    print(f"EN: {text}")
    print(f"TE: {translated}")
    print()

from transformers import pipeline

translator = pipeline(
    "translation",
    model="facebook/nllb-200-distilled-600M"
)

result = translator(
    "Machine learning is changing the world.",
    src_lang="eng_Latn",
    tgt_lang="tel_Telu"
)

print(result[0]["translation_text"])

